// <auto-generated />
namespace Tingle_WebForms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddOrderCancellation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOrderCancellation));
        
        string IMigrationMetadata.Id
        {
            get { return "201411240450227_AddOrderCancellation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
