// <auto-generated />
namespace Tingle_WebForms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Updates20150316 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updates20150316));
        
        string IMigrationMetadata.Id
        {
            get { return "201503170024290_Updates20150316"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
