// <auto-generated />
namespace Tingle_WebForms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FormPermissions_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FormPermissions_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201502190332503_FormPermissions_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
