// <auto-generated />
namespace Tingle_WebForms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixPlantIssue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixPlantIssue));
        
        string IMigrationMetadata.Id
        {
            get { return "201503110253016_FixPlantIssue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
