// <auto-generated />
namespace Tingle_WebForms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Comments_Update21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Comments_Update21));
        
        string IMigrationMetadata.Id
        {
            get { return "201502222219459_Comments_Update21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
